[package]
name = "clipboard-sync-lite"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.29"
wl-clipboard-rs = "0.9.2"
x11-clipboard = "0.9.3"
x11rb = { version = "0.13.2", features = ["xfixes"] }
